### ISSUE TITLE
Getting "Not a valid plugin" under Omeka 2.4.1

### ISSUE THREAD

**Issue by cherveny** [UCSCLibrary/BulkMetadataEditor#14]
Files copied to the plugin directory, I log in as a superadmin, go to plugins, and only BulkMetaDataEditor gets the error "not a valid plugin."  Please let me know if you'd like any additional info.

**Comment by Daniel-KM** [comment]
Hi,

When downloading a plugin from Github, you have to rename the folder name to the name of the plugin : "BulkMetadataEditor".

Sincerely,

Daniel Berthereau
Infodoc & Knowledge managemen

**Comment by cherveny** [comment]
Directory is named properly when error occurs.  Note I did download the zip off the omeka plugins site, rather than github. (https://omeka.org/add-ons/plugins/)   I'll try downloading from here, see if there's a difference between the versions.

**Comment by NedHenry** [comment]
Have you tried changing the file permissions? I got the same error after unzipping the latest version of the plugin from Omeka.org, until I realized that the unzip utility was creating the files so that my web server couldn't read or access them. Try the following, swapping in the path of your plugins folder:
`chmod -R a+x /var/www/html/omeka/plugins/BulkMetadataEditor`

**Comment by cherveny** [comment]
Good thought ned. Will double check the permissions

**Comment by cherveny** [comment]
Looks like some permissions were too low.  I've changed the owner of the files to the apache owner, and opened the permissions as well, both recursively, but still get the same error message.  New to Omeka in general, does it have an error log somewhere it leaves when it tries to parse plugins?

**Comment by cherveny** [comment]
Opps.  My bad.  Changed the permissions on everything below the top level BulkMetadataEditor directory, but **forgot to change the permissions on the top level directory itself!**  Changed it, and poof, the plugin is now working.  Thank you for your suggestions and help in getting it working.
