### ISSUE TITLE
Bulk Metadata Editor didn't work with Omeka 2.5

### ISSUE THREAD

**Issue by level-5** [UCSCLibrary/BulkMetadataEditor#16]
Hi, since I upgraded to 2.5 the Bulk Metadata Editor Plugin didn't work anymore. I still get the Message "The requested changes are applied to the database one by one in the background. Check logs for success and errors." - but no changes to my data where realized. Any suggestions are welcome best jan

**Comment by NedHenry** [comment]
Thanks for reporting this. We haven't tested this plugin thoroughly on
Omeka 2.5 yet, and I suspect this is caused by some error reporting changes
in the new version. We hope to have time to update the plugin soon, and
will certainly welcome pull requests to address the problem in the mean
time.
Best,
Ned Henry

**Comment by level-5** [comment]
Thanks for your quick response. 
Your plugin is a great improvement to omeka!
Best Jan

**Comment by Daniel-KM** [comment]
You may have to set it in the main config file of Omeka (application/config/config.ini).

**Comment by NedHenry** [comment]
Sorry for the slow reply here! Our development resources are a bit maxed
out at the moment, and we're having trouble finding time to maintain these
plugins very well. I will test this when I get a free moment; if any of our
users wants to verify whether this plugin works with 2.6, that would be
awesome.
Thanks!
Ned

**Comment by theecrit** [comment]
@NedHenry Absolutely understood; thanks for letting me know. I haven't yet upgraded to 2.6 (mostly due to extenuating circumstances other than just plugin compatibility). If and when I do, I'll be sure to follow-up here.

**Comment by DBinaghi** [comment]
The plugin is working fine with up to newest Omeka version (3.0.3). Please let us know if you're still experiencing issues.
