### ISSUE TITLE
BulkMetadataEditor regexpr not working

### ISSUE THREAD

**Issue by pabolitox** [UCSCLibrary/BulkMetadataEditor#20]
Hello,

I tried to use the option: "Search and replace text" with "Use regular expressions" but it does not seems to accept any kind of regexpr.

I did validate the ones I wanted in a regexpr validator so I am sure they are OK. 

Regards

**Comment by DBinaghi** [comment]
Hi. The find/replace option with regular expressions seems to be working fine. Could you please give us an example of the expression you're using?
