### ISSUE TITLE
BulkMetadataEditor.zip v2.9 missing views/helpers/BulkEdit.php

### ISSUE THREAD

**Issue by kloor** [UCSCLibrary/BulkMetadataEditor#22]
The BulkMetadataEditor.zip file for [release v2.9](https://github.com/UCSCLibrary/BulkMetadataEditor/releases/tag/v2.9) is missing the views/helpers/BulkEdit.php file. The Source Code (zip) file does include it.

**Comment by DBinaghi** [comment]
Thanks for this, I'll immediately create a new release.
